language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alongal/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alongal/client-test npm test

after_sucess:
  - docker build -t alongal/multi-client ./client
  - docker build -t alongal/multi-nginx ./nginx
  - docker build -t alongal/multi-server ./server
  - docker build -t alongal/multi-worker ./worker
  # LOGIN in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker-hub
  - docker push alongal/multi-client
  - docker push alongal/multi-nginx
  - docker push alongal/multi-server
  - docker push alongal/multi-worker
